export const HANDLE_SUBMIT = "HANDLE_SUBMIT";
export const HANDLE_EDIT = "HANDLE_EDIT";
export const HANDLE_DELETE = "HANDLE_DELETE";
export const HANDLE_CLEAR = "HANDLE_CLEAR";
export const HANDLE_ALERT_TIMER = "HANDLE_ALERT_TIMER";
export const GET_LOCAL_STORAGE = "GET_LOCAL_STORAGE";
